namespace GeometryDashAPI.Tests.TestObjects
{
    public class LargeObject : GameObject
    {
        [GameProperty("1")] public int x1 { get; set; }
        [GameProperty("2")] public int x2 { get; set; }
        [GameProperty("3")] public int x3 { get; set; }
        [GameProperty("4")] public int x4 { get; set; }
        [GameProperty("5")] public int x5 { get; set; }
        [GameProperty("6")] public int x6 { get; set; }
        [GameProperty("7")] public int x7 { get; set; }
        [GameProperty("8")] public int x8 { get; set; }
        [GameProperty("9")] public int x9 { get; set; }
        [GameProperty("10")] public int x10 { get; set; }
        [GameProperty("11")] public int x11 { get; set; }
        [GameProperty("12")] public int x12 { get; set; }
        [GameProperty("13")] public int x13 { get; set; }
        [GameProperty("14")] public int x14 { get; set; }
        [GameProperty("15")] public int x15 { get; set; }
        [GameProperty("16")] public int x16 { get; set; }
        [GameProperty("17")] public int x17 { get; set; }
        [GameProperty("18")] public int x18 { get; set; }
        [GameProperty("19")] public int x19 { get; set; }
        [GameProperty("20")] public int x20 { get; set; }
        [GameProperty("21")] public int x21 { get; set; }
        [GameProperty("22")] public int x22 { get; set; }
        [GameProperty("23")] public int x23 { get; set; }
        [GameProperty("24")] public int x24 { get; set; }
        [GameProperty("25")] public int x25 { get; set; }
        [GameProperty("26")] public int x26 { get; set; }
        [GameProperty("27")] public int x27 { get; set; }
        [GameProperty("28")] public int x28 { get; set; }
        [GameProperty("29")] public int x29 { get; set; }
        [GameProperty("30")] public int x30 { get; set; }
        [GameProperty("31")] public int x31 { get; set; }
        [GameProperty("32")] public int x32 { get; set; }
        [GameProperty("33")] public int x33 { get; set; }
        [GameProperty("34")] public int x34 { get; set; }
        [GameProperty("35")] public int x35 { get; set; }
        [GameProperty("36")] public int x36 { get; set; }
        [GameProperty("37")] public int x37 { get; set; }
        [GameProperty("38")] public int x38 { get; set; }
        [GameProperty("39")] public int x39 { get; set; }
        [GameProperty("40")] public int x40 { get; set; }
        [GameProperty("41")] public int x41 { get; set; }
        [GameProperty("42")] public int x42 { get; set; }
        [GameProperty("43")] public int x43 { get; set; }
        [GameProperty("44")] public int x44 { get; set; }
        [GameProperty("45")] public int x45 { get; set; }
        [GameProperty("46")] public int x46 { get; set; }
        [GameProperty("47")] public int x47 { get; set; }
        [GameProperty("48")] public int x48 { get; set; }
        [GameProperty("49")] public int x49 { get; set; }
        [GameProperty("50")] public int x50 { get; set; }
        [GameProperty("51")] public int x51 { get; set; }
        [GameProperty("52")] public int x52 { get; set; }
        [GameProperty("53")] public int x53 { get; set; }
        [GameProperty("54")] public int x54 { get; set; }
        [GameProperty("55")] public int x55 { get; set; }
        [GameProperty("56")] public int x56 { get; set; }
        [GameProperty("57")] public int x57 { get; set; }
        [GameProperty("58")] public int x58 { get; set; }
        [GameProperty("59")] public int x59 { get; set; }
        [GameProperty("60")] public int x60 { get; set; }
        [GameProperty("61")] public int x61 { get; set; }
        [GameProperty("62")] public int x62 { get; set; }
        [GameProperty("63")] public int x63 { get; set; }
        [GameProperty("64")] public int x64 { get; set; }
        [GameProperty("65")] public int x65 { get; set; }
        [GameProperty("66")] public int x66 { get; set; }
        [GameProperty("67")] public int x67 { get; set; }
        [GameProperty("68")] public int x68 { get; set; }
        [GameProperty("69")] public int x69 { get; set; }
        [GameProperty("70")] public int x70 { get; set; }
        [GameProperty("71")] public int x71 { get; set; }
        [GameProperty("72")] public int x72 { get; set; }
        [GameProperty("73")] public int x73 { get; set; }
        [GameProperty("74")] public int x74 { get; set; }
        [GameProperty("75")] public int x75 { get; set; }
        [GameProperty("76")] public int x76 { get; set; }
        [GameProperty("77")] public int x77 { get; set; }
        [GameProperty("78")] public int x78 { get; set; }
        [GameProperty("79")] public int x79 { get; set; }
        [GameProperty("80")] public int x80 { get; set; }
        [GameProperty("81")] public int x81 { get; set; }
        [GameProperty("82")] public int x82 { get; set; }
        [GameProperty("83")] public int x83 { get; set; }
        [GameProperty("84")] public int x84 { get; set; }
        [GameProperty("85")] public int x85 { get; set; }
        [GameProperty("86")] public int x86 { get; set; }
        [GameProperty("87")] public int x87 { get; set; }
        [GameProperty("88")] public int x88 { get; set; }
        [GameProperty("89")] public int x89 { get; set; }
        [GameProperty("90")] public int x90 { get; set; }
        [GameProperty("91")] public int x91 { get; set; }
        [GameProperty("92")] public int x92 { get; set; }
        [GameProperty("93")] public int x93 { get; set; }
        [GameProperty("94")] public int x94 { get; set; }
        [GameProperty("95")] public int x95 { get; set; }
        [GameProperty("96")] public int x96 { get; set; }
        [GameProperty("97")] public int x97 { get; set; }
        [GameProperty("98")] public int x98 { get; set; }
        [GameProperty("99")] public int x99 { get; set; }
        [GameProperty("100")] public int x100 { get; set; }
        [GameProperty("101")] public int x101 { get; set; }
        [GameProperty("102")] public int x102 { get; set; }
        [GameProperty("103")] public int x103 { get; set; }
        [GameProperty("104")] public int x104 { get; set; }
        [GameProperty("105")] public int x105 { get; set; }
        [GameProperty("106")] public int x106 { get; set; }
        [GameProperty("107")] public int x107 { get; set; }
        [GameProperty("108")] public int x108 { get; set; }
        [GameProperty("109")] public int x109 { get; set; }
        [GameProperty("110")] public int x110 { get; set; }
        [GameProperty("111")] public int x111 { get; set; }
        [GameProperty("112")] public int x112 { get; set; }
        [GameProperty("113")] public int x113 { get; set; }
        [GameProperty("114")] public int x114 { get; set; }
        [GameProperty("115")] public int x115 { get; set; }
        [GameProperty("116")] public int x116 { get; set; }
        [GameProperty("117")] public int x117 { get; set; }
        [GameProperty("118")] public int x118 { get; set; }
        [GameProperty("119")] public int x119 { get; set; }
        [GameProperty("120")] public int x120 { get; set; }
        [GameProperty("121")] public int x121 { get; set; }
        [GameProperty("122")] public int x122 { get; set; }
        [GameProperty("123")] public int x123 { get; set; }
        [GameProperty("124")] public int x124 { get; set; }
        [GameProperty("125")] public int x125 { get; set; }
        [GameProperty("126")] public int x126 { get; set; }
        [GameProperty("127")] public int x127 { get; set; }
        [GameProperty("128")] public int x128 { get; set; }
        [GameProperty("129")] public int x129 { get; set; }
        [GameProperty("130")] public int x130 { get; set; }
        [GameProperty("131")] public int x131 { get; set; }
        [GameProperty("132")] public int x132 { get; set; }
        [GameProperty("133")] public int x133 { get; set; }
        [GameProperty("134")] public int x134 { get; set; }
        [GameProperty("135")] public int x135 { get; set; }
        [GameProperty("136")] public int x136 { get; set; }
        [GameProperty("137")] public int x137 { get; set; }
        [GameProperty("138")] public int x138 { get; set; }
        [GameProperty("139")] public int x139 { get; set; }
        [GameProperty("140")] public int x140 { get; set; }
        [GameProperty("141")] public int x141 { get; set; }
        [GameProperty("142")] public int x142 { get; set; }
        [GameProperty("143")] public int x143 { get; set; }
        [GameProperty("144")] public int x144 { get; set; }
        [GameProperty("145")] public int x145 { get; set; }
        [GameProperty("146")] public int x146 { get; set; }
        [GameProperty("147")] public int x147 { get; set; }
        [GameProperty("148")] public int x148 { get; set; }
        [GameProperty("149")] public int x149 { get; set; }
        [GameProperty("150")] public int x150 { get; set; }
        [GameProperty("151")] public int x151 { get; set; }
        [GameProperty("152")] public int x152 { get; set; }
        [GameProperty("153")] public int x153 { get; set; }
        [GameProperty("154")] public int x154 { get; set; }
        [GameProperty("155")] public int x155 { get; set; }
        [GameProperty("156")] public int x156 { get; set; }
        [GameProperty("157")] public int x157 { get; set; }
        [GameProperty("158")] public int x158 { get; set; }
        [GameProperty("159")] public int x159 { get; set; }
        [GameProperty("160")] public int x160 { get; set; }
        [GameProperty("161")] public int x161 { get; set; }
        [GameProperty("162")] public int x162 { get; set; }
        [GameProperty("163")] public int x163 { get; set; }
        [GameProperty("164")] public int x164 { get; set; }
        [GameProperty("165")] public int x165 { get; set; }
        [GameProperty("166")] public int x166 { get; set; }
        [GameProperty("167")] public int x167 { get; set; }
        [GameProperty("168")] public int x168 { get; set; }
        [GameProperty("169")] public int x169 { get; set; }
        [GameProperty("170")] public int x170 { get; set; }
        [GameProperty("171")] public int x171 { get; set; }
        [GameProperty("172")] public int x172 { get; set; }
        [GameProperty("173")] public int x173 { get; set; }
        [GameProperty("174")] public int x174 { get; set; }
        [GameProperty("175")] public int x175 { get; set; }
        [GameProperty("176")] public int x176 { get; set; }
        [GameProperty("177")] public int x177 { get; set; }
        [GameProperty("178")] public int x178 { get; set; }
        [GameProperty("179")] public int x179 { get; set; }
        [GameProperty("180")] public int x180 { get; set; }
        [GameProperty("181")] public int x181 { get; set; }
        [GameProperty("182")] public int x182 { get; set; }
        [GameProperty("183")] public int x183 { get; set; }
        [GameProperty("184")] public int x184 { get; set; }
        [GameProperty("185")] public int x185 { get; set; }
        [GameProperty("186")] public int x186 { get; set; }
        [GameProperty("187")] public int x187 { get; set; }
        [GameProperty("188")] public int x188 { get; set; }
        [GameProperty("189")] public int x189 { get; set; }
        [GameProperty("190")] public int x190 { get; set; }
        [GameProperty("191")] public int x191 { get; set; }
        [GameProperty("192")] public int x192 { get; set; }
        [GameProperty("193")] public int x193 { get; set; }
        [GameProperty("194")] public int x194 { get; set; }
        [GameProperty("195")] public int x195 { get; set; }
        [GameProperty("196")] public int x196 { get; set; }
        [GameProperty("197")] public int x197 { get; set; }
        [GameProperty("198")] public int x198 { get; set; }
        [GameProperty("199")] public int x199 { get; set; }
        [GameProperty("200")] public int x200 { get; set; }
        [GameProperty("201")] public int x201 { get; set; }
        [GameProperty("202")] public int x202 { get; set; }
        [GameProperty("203")] public int x203 { get; set; }
        [GameProperty("204")] public int x204 { get; set; }
        [GameProperty("205")] public int x205 { get; set; }
        [GameProperty("206")] public int x206 { get; set; }
        [GameProperty("207")] public int x207 { get; set; }
        [GameProperty("208")] public int x208 { get; set; }
        [GameProperty("209")] public int x209 { get; set; }
        [GameProperty("210")] public int x210 { get; set; }
        [GameProperty("211")] public int x211 { get; set; }
        [GameProperty("212")] public int x212 { get; set; }
        [GameProperty("213")] public int x213 { get; set; }
        [GameProperty("214")] public int x214 { get; set; }
        [GameProperty("215")] public int x215 { get; set; }
        [GameProperty("216")] public int x216 { get; set; }
        [GameProperty("217")] public int x217 { get; set; }
        [GameProperty("218")] public int x218 { get; set; }
        [GameProperty("219")] public int x219 { get; set; }
        [GameProperty("220")] public int x220 { get; set; }
        [GameProperty("221")] public int x221 { get; set; }
        [GameProperty("222")] public int x222 { get; set; }
        [GameProperty("223")] public int x223 { get; set; }
        [GameProperty("224")] public int x224 { get; set; }
        [GameProperty("225")] public int x225 { get; set; }
        [GameProperty("226")] public int x226 { get; set; }
        [GameProperty("227")] public int x227 { get; set; }
        [GameProperty("228")] public int x228 { get; set; }
        [GameProperty("229")] public int x229 { get; set; }
        [GameProperty("230")] public int x230 { get; set; }
        [GameProperty("231")] public int x231 { get; set; }
        [GameProperty("232")] public int x232 { get; set; }
        [GameProperty("233")] public int x233 { get; set; }
        [GameProperty("234")] public int x234 { get; set; }
        [GameProperty("235")] public int x235 { get; set; }
        [GameProperty("236")] public int x236 { get; set; }
        [GameProperty("237")] public int x237 { get; set; }
        [GameProperty("238")] public int x238 { get; set; }
        [GameProperty("239")] public int x239 { get; set; }
        [GameProperty("240")] public int x240 { get; set; }
        [GameProperty("241")] public int x241 { get; set; }
        [GameProperty("242")] public int x242 { get; set; }
        [GameProperty("243")] public int x243 { get; set; }
        [GameProperty("244")] public int x244 { get; set; }
        [GameProperty("245")] public int x245 { get; set; }
        [GameProperty("246")] public int x246 { get; set; }
        [GameProperty("247")] public int x247 { get; set; }
        [GameProperty("248")] public int x248 { get; set; }
        [GameProperty("249")] public int x249 { get; set; }
        [GameProperty("250")] public int x250 { get; set; }
        [GameProperty("251")] public int x251 { get; set; }
        [GameProperty("252")] public int x252 { get; set; }
        [GameProperty("253")] public int x253 { get; set; }
        [GameProperty("254")] public int x254 { get; set; }
        [GameProperty("255")] public int x255 { get; set; }
        [GameProperty("256")] public int x256 { get; set; }
        [GameProperty("257")] public int x257 { get; set; }
        [GameProperty("258")] public int x258 { get; set; }
        [GameProperty("259")] public int x259 { get; set; }
        [GameProperty("260")] public int x260 { get; set; }
        [GameProperty("261")] public int x261 { get; set; }
        [GameProperty("262")] public int x262 { get; set; }
        [GameProperty("263")] public int x263 { get; set; }
        [GameProperty("264")] public int x264 { get; set; }
        [GameProperty("265")] public int x265 { get; set; }
        [GameProperty("266")] public int x266 { get; set; }
        [GameProperty("267")] public int x267 { get; set; }
        [GameProperty("268")] public int x268 { get; set; }
        [GameProperty("269")] public int x269 { get; set; }
        [GameProperty("270")] public int x270 { get; set; }
        [GameProperty("271")] public int x271 { get; set; }
        [GameProperty("272")] public int x272 { get; set; }
        [GameProperty("273")] public int x273 { get; set; }
        [GameProperty("274")] public int x274 { get; set; }
        [GameProperty("275")] public int x275 { get; set; }
        [GameProperty("276")] public int x276 { get; set; }
        [GameProperty("277")] public int x277 { get; set; }
        [GameProperty("278")] public int x278 { get; set; }
        [GameProperty("279")] public int x279 { get; set; }
        [GameProperty("280")] public int x280 { get; set; }
        [GameProperty("281")] public int x281 { get; set; }
        [GameProperty("282")] public int x282 { get; set; }
        [GameProperty("283")] public int x283 { get; set; }
        [GameProperty("284")] public int x284 { get; set; }
        [GameProperty("285")] public int x285 { get; set; }
        [GameProperty("286")] public int x286 { get; set; }
        [GameProperty("287")] public int x287 { get; set; }
        [GameProperty("288")] public int x288 { get; set; }
        [GameProperty("289")] public int x289 { get; set; }
        [GameProperty("290")] public int x290 { get; set; }
        [GameProperty("291")] public int x291 { get; set; }
        [GameProperty("292")] public int x292 { get; set; }
        [GameProperty("293")] public int x293 { get; set; }
        [GameProperty("294")] public int x294 { get; set; }
        [GameProperty("295")] public int x295 { get; set; }
        [GameProperty("296")] public int x296 { get; set; }
        [GameProperty("297")] public int x297 { get; set; }
        [GameProperty("298")] public int x298 { get; set; }
        [GameProperty("299")] public int x299 { get; set; }
        [GameProperty("300")] public int x300 { get; set; }
        [GameProperty("301")] public int x301 { get; set; }
        [GameProperty("302")] public int x302 { get; set; }
        [GameProperty("303")] public int x303 { get; set; }
        [GameProperty("304")] public int x304 { get; set; }
        [GameProperty("305")] public int x305 { get; set; }
        [GameProperty("306")] public int x306 { get; set; }
        [GameProperty("307")] public int x307 { get; set; }
        [GameProperty("308")] public int x308 { get; set; }
        [GameProperty("309")] public int x309 { get; set; }
        [GameProperty("310")] public int x310 { get; set; }
        [GameProperty("311")] public int x311 { get; set; }
        [GameProperty("312")] public int x312 { get; set; }
        [GameProperty("313")] public int x313 { get; set; }
        [GameProperty("314")] public int x314 { get; set; }
        [GameProperty("315")] public int x315 { get; set; }
        [GameProperty("316")] public int x316 { get; set; }
        [GameProperty("317")] public int x317 { get; set; }
        [GameProperty("318")] public int x318 { get; set; }
        [GameProperty("319")] public int x319 { get; set; }
        [GameProperty("320")] public int x320 { get; set; }
        [GameProperty("321")] public int x321 { get; set; }
        [GameProperty("322")] public int x322 { get; set; }
        [GameProperty("323")] public int x323 { get; set; }
        [GameProperty("324")] public int x324 { get; set; }
        [GameProperty("325")] public int x325 { get; set; }
        [GameProperty("326")] public int x326 { get; set; }
        [GameProperty("327")] public int x327 { get; set; }
        [GameProperty("328")] public int x328 { get; set; }
        [GameProperty("329")] public int x329 { get; set; }
        [GameProperty("330")] public int x330 { get; set; }
        [GameProperty("331")] public int x331 { get; set; }
        [GameProperty("332")] public int x332 { get; set; }
        [GameProperty("333")] public int x333 { get; set; }
        [GameProperty("334")] public int x334 { get; set; }
        [GameProperty("335")] public int x335 { get; set; }
        [GameProperty("336")] public int x336 { get; set; }
        [GameProperty("337")] public int x337 { get; set; }
        [GameProperty("338")] public int x338 { get; set; }
        [GameProperty("339")] public int x339 { get; set; }
        [GameProperty("340")] public int x340 { get; set; }
        [GameProperty("341")] public int x341 { get; set; }
        [GameProperty("342")] public int x342 { get; set; }
        [GameProperty("343")] public int x343 { get; set; }
        [GameProperty("344")] public int x344 { get; set; }
        [GameProperty("345")] public int x345 { get; set; }
        [GameProperty("346")] public int x346 { get; set; }
        [GameProperty("347")] public int x347 { get; set; }
        [GameProperty("348")] public int x348 { get; set; }
        [GameProperty("349")] public int x349 { get; set; }
        [GameProperty("350")] public int x350 { get; set; }
        [GameProperty("351")] public int x351 { get; set; }
        [GameProperty("352")] public int x352 { get; set; }
        [GameProperty("353")] public int x353 { get; set; }
        [GameProperty("354")] public int x354 { get; set; }
        [GameProperty("355")] public int x355 { get; set; }
        [GameProperty("356")] public int x356 { get; set; }
        [GameProperty("357")] public int x357 { get; set; }
        [GameProperty("358")] public int x358 { get; set; }
        [GameProperty("359")] public int x359 { get; set; }
        [GameProperty("360")] public int x360 { get; set; }
        [GameProperty("361")] public int x361 { get; set; }
        [GameProperty("362")] public int x362 { get; set; }
        [GameProperty("363")] public int x363 { get; set; }
        [GameProperty("364")] public int x364 { get; set; }
        [GameProperty("365")] public int x365 { get; set; }
        [GameProperty("366")] public int x366 { get; set; }
        [GameProperty("367")] public int x367 { get; set; }
        [GameProperty("368")] public int x368 { get; set; }
        [GameProperty("369")] public int x369 { get; set; }
        [GameProperty("370")] public int x370 { get; set; }
        [GameProperty("371")] public int x371 { get; set; }
        [GameProperty("372")] public int x372 { get; set; }
        [GameProperty("373")] public int x373 { get; set; }
        [GameProperty("374")] public int x374 { get; set; }
        [GameProperty("375")] public int x375 { get; set; }
        [GameProperty("376")] public int x376 { get; set; }
        [GameProperty("377")] public int x377 { get; set; }
        [GameProperty("378")] public int x378 { get; set; }
        [GameProperty("379")] public int x379 { get; set; }
        [GameProperty("380")] public int x380 { get; set; }
        [GameProperty("381")] public int x381 { get; set; }
        [GameProperty("382")] public int x382 { get; set; }
        [GameProperty("383")] public int x383 { get; set; }
        [GameProperty("384")] public int x384 { get; set; }
        [GameProperty("385")] public int x385 { get; set; }
        [GameProperty("386")] public int x386 { get; set; }
        [GameProperty("387")] public int x387 { get; set; }
        [GameProperty("388")] public int x388 { get; set; }
        [GameProperty("389")] public int x389 { get; set; }
        [GameProperty("390")] public int x390 { get; set; }
        [GameProperty("391")] public int x391 { get; set; }
        [GameProperty("392")] public int x392 { get; set; }
        [GameProperty("393")] public int x393 { get; set; }
        [GameProperty("394")] public int x394 { get; set; }
        [GameProperty("395")] public int x395 { get; set; }
        [GameProperty("396")] public int x396 { get; set; }
        [GameProperty("397")] public int x397 { get; set; }
        [GameProperty("398")] public int x398 { get; set; }
        [GameProperty("399")] public int x399 { get; set; }
        [GameProperty("400")] public int x400 { get; set; }
        [GameProperty("401")] public int x401 { get; set; }
        [GameProperty("402")] public int x402 { get; set; }
        [GameProperty("403")] public int x403 { get; set; }
        [GameProperty("404")] public int x404 { get; set; }
        [GameProperty("405")] public int x405 { get; set; }
        [GameProperty("406")] public int x406 { get; set; }
        [GameProperty("407")] public int x407 { get; set; }
        [GameProperty("408")] public int x408 { get; set; }
        [GameProperty("409")] public int x409 { get; set; }
        [GameProperty("410")] public int x410 { get; set; }
        [GameProperty("411")] public int x411 { get; set; }
        [GameProperty("412")] public int x412 { get; set; }
        [GameProperty("413")] public int x413 { get; set; }
        [GameProperty("414")] public int x414 { get; set; }
        [GameProperty("415")] public int x415 { get; set; }
        [GameProperty("416")] public int x416 { get; set; }
        [GameProperty("417")] public int x417 { get; set; }
        [GameProperty("418")] public int x418 { get; set; }
        [GameProperty("419")] public int x419 { get; set; }
        [GameProperty("420")] public int x420 { get; set; }
        [GameProperty("421")] public int x421 { get; set; }
        [GameProperty("422")] public int x422 { get; set; }
        [GameProperty("423")] public int x423 { get; set; }
        [GameProperty("424")] public int x424 { get; set; }
        [GameProperty("425")] public int x425 { get; set; }
        [GameProperty("426")] public int x426 { get; set; }
        [GameProperty("427")] public int x427 { get; set; }
        [GameProperty("428")] public int x428 { get; set; }
        [GameProperty("429")] public int x429 { get; set; }
        [GameProperty("430")] public int x430 { get; set; }
        [GameProperty("431")] public int x431 { get; set; }
        [GameProperty("432")] public int x432 { get; set; }
        [GameProperty("433")] public int x433 { get; set; }
        [GameProperty("434")] public int x434 { get; set; }
        [GameProperty("435")] public int x435 { get; set; }
        [GameProperty("436")] public int x436 { get; set; }
        [GameProperty("437")] public int x437 { get; set; }
        [GameProperty("438")] public int x438 { get; set; }
        [GameProperty("439")] public int x439 { get; set; }
        [GameProperty("440")] public int x440 { get; set; }
        [GameProperty("441")] public int x441 { get; set; }
        [GameProperty("442")] public int x442 { get; set; }
        [GameProperty("443")] public int x443 { get; set; }
        [GameProperty("444")] public int x444 { get; set; }
        [GameProperty("445")] public int x445 { get; set; }
        [GameProperty("446")] public int x446 { get; set; }
        [GameProperty("447")] public int x447 { get; set; }
        [GameProperty("448")] public int x448 { get; set; }
        [GameProperty("449")] public int x449 { get; set; }
        [GameProperty("450")] public int x450 { get; set; }
        [GameProperty("451")] public int x451 { get; set; }
        [GameProperty("452")] public int x452 { get; set; }
        [GameProperty("453")] public int x453 { get; set; }
        [GameProperty("454")] public int x454 { get; set; }
        [GameProperty("455")] public int x455 { get; set; }
        [GameProperty("456")] public int x456 { get; set; }
        [GameProperty("457")] public int x457 { get; set; }
        [GameProperty("458")] public int x458 { get; set; }
        [GameProperty("459")] public int x459 { get; set; }
        [GameProperty("460")] public int x460 { get; set; }
        [GameProperty("461")] public int x461 { get; set; }
        [GameProperty("462")] public int x462 { get; set; }
        [GameProperty("463")] public int x463 { get; set; }
        [GameProperty("464")] public int x464 { get; set; }
        [GameProperty("465")] public int x465 { get; set; }
        [GameProperty("466")] public int x466 { get; set; }
        [GameProperty("467")] public int x467 { get; set; }
        [GameProperty("468")] public int x468 { get; set; }
        [GameProperty("469")] public int x469 { get; set; }
        [GameProperty("470")] public int x470 { get; set; }
        [GameProperty("471")] public int x471 { get; set; }
        [GameProperty("472")] public int x472 { get; set; }
        [GameProperty("473")] public int x473 { get; set; }
        [GameProperty("474")] public int x474 { get; set; }
        [GameProperty("475")] public int x475 { get; set; }
        [GameProperty("476")] public int x476 { get; set; }
        [GameProperty("477")] public int x477 { get; set; }
        [GameProperty("478")] public int x478 { get; set; }
        [GameProperty("479")] public int x479 { get; set; }
        [GameProperty("480")] public int x480 { get; set; }
        [GameProperty("481")] public int x481 { get; set; }
        [GameProperty("482")] public int x482 { get; set; }
        [GameProperty("483")] public int x483 { get; set; }
        [GameProperty("484")] public int x484 { get; set; }
        [GameProperty("485")] public int x485 { get; set; }
        [GameProperty("486")] public int x486 { get; set; }
        [GameProperty("487")] public int x487 { get; set; }
        [GameProperty("488")] public int x488 { get; set; }
        [GameProperty("489")] public int x489 { get; set; }
        [GameProperty("490")] public int x490 { get; set; }
        [GameProperty("491")] public int x491 { get; set; }
        [GameProperty("492")] public int x492 { get; set; }
        [GameProperty("493")] public int x493 { get; set; }
        [GameProperty("494")] public int x494 { get; set; }
        [GameProperty("495")] public int x495 { get; set; }
        [GameProperty("496")] public int x496 { get; set; }
        [GameProperty("497")] public int x497 { get; set; }
        [GameProperty("498")] public int x498 { get; set; }
        [GameProperty("499")] public int x499 { get; set; }
        [GameProperty("500")] public int x500 { get; set; }
        [GameProperty("501")] public int x501 { get; set; }
        [GameProperty("502")] public int x502 { get; set; }
        [GameProperty("503")] public int x503 { get; set; }
        [GameProperty("504")] public int x504 { get; set; }
        [GameProperty("505")] public int x505 { get; set; }
        [GameProperty("506")] public int x506 { get; set; }
        [GameProperty("507")] public int x507 { get; set; }
        [GameProperty("508")] public int x508 { get; set; }
        [GameProperty("509")] public int x509 { get; set; }
        [GameProperty("510")] public int x510 { get; set; }
        [GameProperty("511")] public int x511 { get; set; }
        [GameProperty("512")] public int x512 { get; set; }
        [GameProperty("513")] public int x513 { get; set; }
        [GameProperty("514")] public int x514 { get; set; }
        [GameProperty("515")] public int x515 { get; set; }
        [GameProperty("516")] public int x516 { get; set; }
        [GameProperty("517")] public int x517 { get; set; }
        [GameProperty("518")] public int x518 { get; set; }
        [GameProperty("519")] public int x519 { get; set; }
        [GameProperty("520")] public int x520 { get; set; }
        [GameProperty("521")] public int x521 { get; set; }
        [GameProperty("522")] public int x522 { get; set; }
        [GameProperty("523")] public int x523 { get; set; }
        [GameProperty("524")] public int x524 { get; set; }
        [GameProperty("525")] public int x525 { get; set; }
        [GameProperty("526")] public int x526 { get; set; }
        [GameProperty("527")] public int x527 { get; set; }
        [GameProperty("528")] public int x528 { get; set; }
        [GameProperty("529")] public int x529 { get; set; }
        [GameProperty("530")] public int x530 { get; set; }
        [GameProperty("531")] public int x531 { get; set; }
        [GameProperty("532")] public int x532 { get; set; }
        [GameProperty("533")] public int x533 { get; set; }
        [GameProperty("534")] public int x534 { get; set; }
        [GameProperty("535")] public int x535 { get; set; }
        [GameProperty("536")] public int x536 { get; set; }
        [GameProperty("537")] public int x537 { get; set; }
        [GameProperty("538")] public int x538 { get; set; }
        [GameProperty("539")] public int x539 { get; set; }
        [GameProperty("540")] public int x540 { get; set; }
        [GameProperty("541")] public int x541 { get; set; }
        [GameProperty("542")] public int x542 { get; set; }
        [GameProperty("543")] public int x543 { get; set; }
        [GameProperty("544")] public int x544 { get; set; }
        [GameProperty("545")] public int x545 { get; set; }
        [GameProperty("546")] public int x546 { get; set; }
        [GameProperty("547")] public int x547 { get; set; }
        [GameProperty("548")] public int x548 { get; set; }
        [GameProperty("549")] public int x549 { get; set; }
        [GameProperty("550")] public int x550 { get; set; }
        [GameProperty("551")] public int x551 { get; set; }
        [GameProperty("552")] public int x552 { get; set; }
        [GameProperty("553")] public int x553 { get; set; }
        [GameProperty("554")] public int x554 { get; set; }
        [GameProperty("555")] public int x555 { get; set; }
        [GameProperty("556")] public int x556 { get; set; }
        [GameProperty("557")] public int x557 { get; set; }
        [GameProperty("558")] public int x558 { get; set; }
        [GameProperty("559")] public int x559 { get; set; }
        [GameProperty("560")] public int x560 { get; set; }
        [GameProperty("561")] public int x561 { get; set; }
        [GameProperty("562")] public int x562 { get; set; }
        [GameProperty("563")] public int x563 { get; set; }
        [GameProperty("564")] public int x564 { get; set; }
        [GameProperty("565")] public int x565 { get; set; }
        [GameProperty("566")] public int x566 { get; set; }
        [GameProperty("567")] public int x567 { get; set; }
        [GameProperty("568")] public int x568 { get; set; }
        [GameProperty("569")] public int x569 { get; set; }
        [GameProperty("570")] public int x570 { get; set; }
        [GameProperty("571")] public int x571 { get; set; }
        [GameProperty("572")] public int x572 { get; set; }
        [GameProperty("573")] public int x573 { get; set; }
        [GameProperty("574")] public int x574 { get; set; }
        [GameProperty("575")] public int x575 { get; set; }
        [GameProperty("576")] public int x576 { get; set; }
        [GameProperty("577")] public int x577 { get; set; }
        [GameProperty("578")] public int x578 { get; set; }
        [GameProperty("579")] public int x579 { get; set; }
        [GameProperty("580")] public int x580 { get; set; }
        [GameProperty("581")] public int x581 { get; set; }
        [GameProperty("582")] public int x582 { get; set; }
        [GameProperty("583")] public int x583 { get; set; }
        [GameProperty("584")] public int x584 { get; set; }
        [GameProperty("585")] public int x585 { get; set; }
        [GameProperty("586")] public int x586 { get; set; }
        [GameProperty("587")] public int x587 { get; set; }
        [GameProperty("588")] public int x588 { get; set; }
        [GameProperty("589")] public int x589 { get; set; }
        [GameProperty("590")] public int x590 { get; set; }
        [GameProperty("591")] public int x591 { get; set; }
        [GameProperty("592")] public int x592 { get; set; }
        [GameProperty("593")] public int x593 { get; set; }
        [GameProperty("594")] public int x594 { get; set; }
        [GameProperty("595")] public int x595 { get; set; }
        [GameProperty("596")] public int x596 { get; set; }
        [GameProperty("597")] public int x597 { get; set; }
        [GameProperty("598")] public int x598 { get; set; }
        [GameProperty("599")] public int x599 { get; set; }
        [GameProperty("600")] public int x600 { get; set; }
        [GameProperty("601")] public int x601 { get; set; }
        [GameProperty("602")] public int x602 { get; set; }
        [GameProperty("603")] public int x603 { get; set; }
        [GameProperty("604")] public int x604 { get; set; }
        [GameProperty("605")] public int x605 { get; set; }
        [GameProperty("606")] public int x606 { get; set; }
        [GameProperty("607")] public int x607 { get; set; }
        [GameProperty("608")] public int x608 { get; set; }
        [GameProperty("609")] public int x609 { get; set; }
        [GameProperty("610")] public int x610 { get; set; }
        [GameProperty("611")] public int x611 { get; set; }
        [GameProperty("612")] public int x612 { get; set; }
        [GameProperty("613")] public int x613 { get; set; }
        [GameProperty("614")] public int x614 { get; set; }
        [GameProperty("615")] public int x615 { get; set; }
        [GameProperty("616")] public int x616 { get; set; }
        [GameProperty("617")] public int x617 { get; set; }
        [GameProperty("618")] public int x618 { get; set; }
        [GameProperty("619")] public int x619 { get; set; }
        [GameProperty("620")] public int x620 { get; set; }
        [GameProperty("621")] public int x621 { get; set; }
        [GameProperty("622")] public int x622 { get; set; }
        [GameProperty("623")] public int x623 { get; set; }
        [GameProperty("624")] public int x624 { get; set; }
        [GameProperty("625")] public int x625 { get; set; }
        [GameProperty("626")] public int x626 { get; set; }
        [GameProperty("627")] public int x627 { get; set; }
        [GameProperty("628")] public int x628 { get; set; }
        [GameProperty("629")] public int x629 { get; set; }
        [GameProperty("630")] public int x630 { get; set; }
        [GameProperty("631")] public int x631 { get; set; }
        [GameProperty("632")] public int x632 { get; set; }
        [GameProperty("633")] public int x633 { get; set; }
        [GameProperty("634")] public int x634 { get; set; }
        [GameProperty("635")] public int x635 { get; set; }
        [GameProperty("636")] public int x636 { get; set; }
        [GameProperty("637")] public int x637 { get; set; }
        [GameProperty("638")] public int x638 { get; set; }
        [GameProperty("639")] public int x639 { get; set; }
        [GameProperty("640")] public int x640 { get; set; }
        [GameProperty("641")] public int x641 { get; set; }
        [GameProperty("642")] public int x642 { get; set; }
        [GameProperty("643")] public int x643 { get; set; }
        [GameProperty("644")] public int x644 { get; set; }
        [GameProperty("645")] public int x645 { get; set; }
        [GameProperty("646")] public int x646 { get; set; }
        [GameProperty("647")] public int x647 { get; set; }
        [GameProperty("648")] public int x648 { get; set; }
        [GameProperty("649")] public int x649 { get; set; }
        [GameProperty("650")] public int x650 { get; set; }
        [GameProperty("651")] public int x651 { get; set; }
        [GameProperty("652")] public int x652 { get; set; }
        [GameProperty("653")] public int x653 { get; set; }
        [GameProperty("654")] public int x654 { get; set; }
        [GameProperty("655")] public int x655 { get; set; }
        [GameProperty("656")] public int x656 { get; set; }
        [GameProperty("657")] public int x657 { get; set; }
        [GameProperty("658")] public int x658 { get; set; }
        [GameProperty("659")] public int x659 { get; set; }
        [GameProperty("660")] public int x660 { get; set; }
        [GameProperty("661")] public int x661 { get; set; }
        [GameProperty("662")] public int x662 { get; set; }
        [GameProperty("663")] public int x663 { get; set; }
        [GameProperty("664")] public int x664 { get; set; }
        [GameProperty("665")] public int x665 { get; set; }
        [GameProperty("666")] public int x666 { get; set; }
        [GameProperty("667")] public int x667 { get; set; }
        [GameProperty("668")] public int x668 { get; set; }
        [GameProperty("669")] public int x669 { get; set; }
        [GameProperty("670")] public int x670 { get; set; }
        [GameProperty("671")] public int x671 { get; set; }
        [GameProperty("672")] public int x672 { get; set; }
        [GameProperty("673")] public int x673 { get; set; }
        [GameProperty("674")] public int x674 { get; set; }
        [GameProperty("675")] public int x675 { get; set; }
        [GameProperty("676")] public int x676 { get; set; }
        [GameProperty("677")] public int x677 { get; set; }
        [GameProperty("678")] public int x678 { get; set; }
        [GameProperty("679")] public int x679 { get; set; }
        [GameProperty("680")] public int x680 { get; set; }
        [GameProperty("681")] public int x681 { get; set; }
        [GameProperty("682")] public int x682 { get; set; }
        [GameProperty("683")] public int x683 { get; set; }
        [GameProperty("684")] public int x684 { get; set; }
        [GameProperty("685")] public int x685 { get; set; }
        [GameProperty("686")] public int x686 { get; set; }
        [GameProperty("687")] public int x687 { get; set; }
        [GameProperty("688")] public int x688 { get; set; }
        [GameProperty("689")] public int x689 { get; set; }
        [GameProperty("690")] public int x690 { get; set; }
        [GameProperty("691")] public int x691 { get; set; }
        [GameProperty("692")] public int x692 { get; set; }
        [GameProperty("693")] public int x693 { get; set; }
        [GameProperty("694")] public int x694 { get; set; }
        [GameProperty("695")] public int x695 { get; set; }
        [GameProperty("696")] public int x696 { get; set; }
        [GameProperty("697")] public int x697 { get; set; }
        [GameProperty("698")] public int x698 { get; set; }
        [GameProperty("699")] public int x699 { get; set; }
        [GameProperty("700")] public int x700 { get; set; }
        [GameProperty("701")] public int x701 { get; set; }
        [GameProperty("702")] public int x702 { get; set; }
        [GameProperty("703")] public int x703 { get; set; }
        [GameProperty("704")] public int x704 { get; set; }
        [GameProperty("705")] public int x705 { get; set; }
        [GameProperty("706")] public int x706 { get; set; }
        [GameProperty("707")] public int x707 { get; set; }
        [GameProperty("708")] public int x708 { get; set; }
        [GameProperty("709")] public int x709 { get; set; }
        [GameProperty("710")] public int x710 { get; set; }
        [GameProperty("711")] public int x711 { get; set; }
        [GameProperty("712")] public int x712 { get; set; }
        [GameProperty("713")] public int x713 { get; set; }
        [GameProperty("714")] public int x714 { get; set; }
        [GameProperty("715")] public int x715 { get; set; }
        [GameProperty("716")] public int x716 { get; set; }
        [GameProperty("717")] public int x717 { get; set; }
        [GameProperty("718")] public int x718 { get; set; }
        [GameProperty("719")] public int x719 { get; set; }
        [GameProperty("720")] public int x720 { get; set; }
        [GameProperty("721")] public int x721 { get; set; }
        [GameProperty("722")] public int x722 { get; set; }
        [GameProperty("723")] public int x723 { get; set; }
        [GameProperty("724")] public int x724 { get; set; }
        [GameProperty("725")] public int x725 { get; set; }
        [GameProperty("726")] public int x726 { get; set; }
        [GameProperty("727")] public int x727 { get; set; }
        [GameProperty("728")] public int x728 { get; set; }
        [GameProperty("729")] public int x729 { get; set; }
        [GameProperty("730")] public int x730 { get; set; }
        [GameProperty("731")] public int x731 { get; set; }
        [GameProperty("732")] public int x732 { get; set; }
        [GameProperty("733")] public int x733 { get; set; }
        [GameProperty("734")] public int x734 { get; set; }
        [GameProperty("735")] public int x735 { get; set; }
        [GameProperty("736")] public int x736 { get; set; }
        [GameProperty("737")] public int x737 { get; set; }
        [GameProperty("738")] public int x738 { get; set; }
        [GameProperty("739")] public int x739 { get; set; }
        [GameProperty("740")] public int x740 { get; set; }
        [GameProperty("741")] public int x741 { get; set; }
        [GameProperty("742")] public int x742 { get; set; }
        [GameProperty("743")] public int x743 { get; set; }
        [GameProperty("744")] public int x744 { get; set; }
        [GameProperty("745")] public int x745 { get; set; }
        [GameProperty("746")] public int x746 { get; set; }
        [GameProperty("747")] public int x747 { get; set; }
        [GameProperty("748")] public int x748 { get; set; }
        [GameProperty("749")] public int x749 { get; set; }
        [GameProperty("750")] public int x750 { get; set; }
        [GameProperty("751")] public int x751 { get; set; }
        [GameProperty("752")] public int x752 { get; set; }
        [GameProperty("753")] public int x753 { get; set; }
        [GameProperty("754")] public int x754 { get; set; }
        [GameProperty("755")] public int x755 { get; set; }
        [GameProperty("756")] public int x756 { get; set; }
        [GameProperty("757")] public int x757 { get; set; }
        [GameProperty("758")] public int x758 { get; set; }
        [GameProperty("759")] public int x759 { get; set; }
        [GameProperty("760")] public int x760 { get; set; }
        [GameProperty("761")] public int x761 { get; set; }
        [GameProperty("762")] public int x762 { get; set; }
        [GameProperty("763")] public int x763 { get; set; }
        [GameProperty("764")] public int x764 { get; set; }
        [GameProperty("765")] public int x765 { get; set; }
        [GameProperty("766")] public int x766 { get; set; }
        [GameProperty("767")] public int x767 { get; set; }
        [GameProperty("768")] public int x768 { get; set; }
        [GameProperty("769")] public int x769 { get; set; }
        [GameProperty("770")] public int x770 { get; set; }
        [GameProperty("771")] public int x771 { get; set; }
        [GameProperty("772")] public int x772 { get; set; }
        [GameProperty("773")] public int x773 { get; set; }
        [GameProperty("774")] public int x774 { get; set; }
        [GameProperty("775")] public int x775 { get; set; }
        [GameProperty("776")] public int x776 { get; set; }
        [GameProperty("777")] public int x777 { get; set; }
        [GameProperty("778")] public int x778 { get; set; }
        [GameProperty("779")] public int x779 { get; set; }
        [GameProperty("780")] public int x780 { get; set; }
        [GameProperty("781")] public int x781 { get; set; }
        [GameProperty("782")] public int x782 { get; set; }
        [GameProperty("783")] public int x783 { get; set; }
        [GameProperty("784")] public int x784 { get; set; }
        [GameProperty("785")] public int x785 { get; set; }
        [GameProperty("786")] public int x786 { get; set; }
        [GameProperty("787")] public int x787 { get; set; }
        [GameProperty("788")] public int x788 { get; set; }
        [GameProperty("789")] public int x789 { get; set; }
        [GameProperty("790")] public int x790 { get; set; }
        [GameProperty("791")] public int x791 { get; set; }
        [GameProperty("792")] public int x792 { get; set; }
        [GameProperty("793")] public int x793 { get; set; }
        [GameProperty("794")] public int x794 { get; set; }
        [GameProperty("795")] public int x795 { get; set; }
        [GameProperty("796")] public int x796 { get; set; }
        [GameProperty("797")] public int x797 { get; set; }
        [GameProperty("798")] public int x798 { get; set; }
        [GameProperty("799")] public int x799 { get; set; }
        [GameProperty("800")] public int x800 { get; set; }
        [GameProperty("801")] public int x801 { get; set; }
        [GameProperty("802")] public int x802 { get; set; }
        [GameProperty("803")] public int x803 { get; set; }
        [GameProperty("804")] public int x804 { get; set; }
        [GameProperty("805")] public int x805 { get; set; }
        [GameProperty("806")] public int x806 { get; set; }
        [GameProperty("807")] public int x807 { get; set; }
        [GameProperty("808")] public int x808 { get; set; }
        [GameProperty("809")] public int x809 { get; set; }
        [GameProperty("810")] public int x810 { get; set; }
        [GameProperty("811")] public int x811 { get; set; }
        [GameProperty("812")] public int x812 { get; set; }
        [GameProperty("813")] public int x813 { get; set; }
        [GameProperty("814")] public int x814 { get; set; }
        [GameProperty("815")] public int x815 { get; set; }
        [GameProperty("816")] public int x816 { get; set; }
        [GameProperty("817")] public int x817 { get; set; }
        [GameProperty("818")] public int x818 { get; set; }
        [GameProperty("819")] public int x819 { get; set; }
        [GameProperty("820")] public int x820 { get; set; }
        [GameProperty("821")] public int x821 { get; set; }
        [GameProperty("822")] public int x822 { get; set; }
        [GameProperty("823")] public int x823 { get; set; }
        [GameProperty("824")] public int x824 { get; set; }
        [GameProperty("825")] public int x825 { get; set; }
        [GameProperty("826")] public int x826 { get; set; }
        [GameProperty("827")] public int x827 { get; set; }
        [GameProperty("828")] public int x828 { get; set; }
        [GameProperty("829")] public int x829 { get; set; }
        [GameProperty("830")] public int x830 { get; set; }
        [GameProperty("831")] public int x831 { get; set; }
        [GameProperty("832")] public int x832 { get; set; }
        [GameProperty("833")] public int x833 { get; set; }
        [GameProperty("834")] public int x834 { get; set; }
        [GameProperty("835")] public int x835 { get; set; }
        [GameProperty("836")] public int x836 { get; set; }
        [GameProperty("837")] public int x837 { get; set; }
        [GameProperty("838")] public int x838 { get; set; }
        [GameProperty("839")] public int x839 { get; set; }
        [GameProperty("840")] public int x840 { get; set; }
        [GameProperty("841")] public int x841 { get; set; }
        [GameProperty("842")] public int x842 { get; set; }
        [GameProperty("843")] public int x843 { get; set; }
        [GameProperty("844")] public int x844 { get; set; }
        [GameProperty("845")] public int x845 { get; set; }
        [GameProperty("846")] public int x846 { get; set; }
        [GameProperty("847")] public int x847 { get; set; }
        [GameProperty("848")] public int x848 { get; set; }
        [GameProperty("849")] public int x849 { get; set; }
        [GameProperty("850")] public int x850 { get; set; }
        [GameProperty("851")] public int x851 { get; set; }
        [GameProperty("852")] public int x852 { get; set; }
        [GameProperty("853")] public int x853 { get; set; }
        [GameProperty("854")] public int x854 { get; set; }
        [GameProperty("855")] public int x855 { get; set; }
        [GameProperty("856")] public int x856 { get; set; }
        [GameProperty("857")] public int x857 { get; set; }
        [GameProperty("858")] public int x858 { get; set; }
        [GameProperty("859")] public int x859 { get; set; }
        [GameProperty("860")] public int x860 { get; set; }
        [GameProperty("861")] public int x861 { get; set; }
        [GameProperty("862")] public int x862 { get; set; }
        [GameProperty("863")] public int x863 { get; set; }
        [GameProperty("864")] public int x864 { get; set; }
        [GameProperty("865")] public int x865 { get; set; }
        [GameProperty("866")] public int x866 { get; set; }
        [GameProperty("867")] public int x867 { get; set; }
        [GameProperty("868")] public int x868 { get; set; }
        [GameProperty("869")] public int x869 { get; set; }
        [GameProperty("870")] public int x870 { get; set; }
        [GameProperty("871")] public int x871 { get; set; }
        [GameProperty("872")] public int x872 { get; set; }
        [GameProperty("873")] public int x873 { get; set; }
        [GameProperty("874")] public int x874 { get; set; }
        [GameProperty("875")] public int x875 { get; set; }
        [GameProperty("876")] public int x876 { get; set; }
        [GameProperty("877")] public int x877 { get; set; }
        [GameProperty("878")] public int x878 { get; set; }
        [GameProperty("879")] public int x879 { get; set; }
        [GameProperty("880")] public int x880 { get; set; }
        [GameProperty("881")] public int x881 { get; set; }
        [GameProperty("882")] public int x882 { get; set; }
        [GameProperty("883")] public int x883 { get; set; }
        [GameProperty("884")] public int x884 { get; set; }
        [GameProperty("885")] public int x885 { get; set; }
        [GameProperty("886")] public int x886 { get; set; }
        [GameProperty("887")] public int x887 { get; set; }
        [GameProperty("888")] public int x888 { get; set; }
        [GameProperty("889")] public int x889 { get; set; }
        [GameProperty("890")] public int x890 { get; set; }
        [GameProperty("891")] public int x891 { get; set; }
        [GameProperty("892")] public int x892 { get; set; }
        [GameProperty("893")] public int x893 { get; set; }
        [GameProperty("894")] public int x894 { get; set; }
        [GameProperty("895")] public int x895 { get; set; }
        [GameProperty("896")] public int x896 { get; set; }
        [GameProperty("897")] public int x897 { get; set; }
        [GameProperty("898")] public int x898 { get; set; }
        [GameProperty("899")] public int x899 { get; set; }
        [GameProperty("900")] public int x900 { get; set; }
        [GameProperty("901")] public int x901 { get; set; }
        [GameProperty("902")] public int x902 { get; set; }
        [GameProperty("903")] public int x903 { get; set; }
        [GameProperty("904")] public int x904 { get; set; }
        [GameProperty("905")] public int x905 { get; set; }
        [GameProperty("906")] public int x906 { get; set; }
        [GameProperty("907")] public int x907 { get; set; }
        [GameProperty("908")] public int x908 { get; set; }
        [GameProperty("909")] public int x909 { get; set; }
        [GameProperty("910")] public int x910 { get; set; }
        [GameProperty("911")] public int x911 { get; set; }
        [GameProperty("912")] public int x912 { get; set; }
        [GameProperty("913")] public int x913 { get; set; }
        [GameProperty("914")] public int x914 { get; set; }
        [GameProperty("915")] public int x915 { get; set; }
        [GameProperty("916")] public int x916 { get; set; }
        [GameProperty("917")] public int x917 { get; set; }
        [GameProperty("918")] public int x918 { get; set; }
        [GameProperty("919")] public int x919 { get; set; }
        [GameProperty("920")] public int x920 { get; set; }
        [GameProperty("921")] public int x921 { get; set; }
        [GameProperty("922")] public int x922 { get; set; }
        [GameProperty("923")] public int x923 { get; set; }
        [GameProperty("924")] public int x924 { get; set; }
        [GameProperty("925")] public int x925 { get; set; }
        [GameProperty("926")] public int x926 { get; set; }
        [GameProperty("927")] public int x927 { get; set; }
        [GameProperty("928")] public int x928 { get; set; }
        [GameProperty("929")] public int x929 { get; set; }
        [GameProperty("930")] public int x930 { get; set; }
        [GameProperty("931")] public int x931 { get; set; }
        [GameProperty("932")] public int x932 { get; set; }
        [GameProperty("933")] public int x933 { get; set; }
        [GameProperty("934")] public int x934 { get; set; }
        [GameProperty("935")] public int x935 { get; set; }
        [GameProperty("936")] public int x936 { get; set; }
        [GameProperty("937")] public int x937 { get; set; }
        [GameProperty("938")] public int x938 { get; set; }
        [GameProperty("939")] public int x939 { get; set; }
        [GameProperty("940")] public int x940 { get; set; }
        [GameProperty("941")] public int x941 { get; set; }
        [GameProperty("942")] public int x942 { get; set; }
        [GameProperty("943")] public int x943 { get; set; }
        [GameProperty("944")] public int x944 { get; set; }
        [GameProperty("945")] public int x945 { get; set; }
        [GameProperty("946")] public int x946 { get; set; }
        [GameProperty("947")] public int x947 { get; set; }
        [GameProperty("948")] public int x948 { get; set; }
        [GameProperty("949")] public int x949 { get; set; }
        [GameProperty("950")] public int x950 { get; set; }
        [GameProperty("951")] public int x951 { get; set; }
        [GameProperty("952")] public int x952 { get; set; }
        [GameProperty("953")] public int x953 { get; set; }
        [GameProperty("954")] public int x954 { get; set; }
        [GameProperty("955")] public int x955 { get; set; }
        [GameProperty("956")] public int x956 { get; set; }
        [GameProperty("957")] public int x957 { get; set; }
        [GameProperty("958")] public int x958 { get; set; }
        [GameProperty("959")] public int x959 { get; set; }
        [GameProperty("960")] public int x960 { get; set; }
        [GameProperty("961")] public int x961 { get; set; }
        [GameProperty("962")] public int x962 { get; set; }
        [GameProperty("963")] public int x963 { get; set; }
        [GameProperty("964")] public int x964 { get; set; }
        [GameProperty("965")] public int x965 { get; set; }
        [GameProperty("966")] public int x966 { get; set; }
        [GameProperty("967")] public int x967 { get; set; }
        [GameProperty("968")] public int x968 { get; set; }
        [GameProperty("969")] public int x969 { get; set; }
        [GameProperty("970")] public int x970 { get; set; }
        [GameProperty("971")] public int x971 { get; set; }
        [GameProperty("972")] public int x972 { get; set; }
        [GameProperty("973")] public int x973 { get; set; }
        [GameProperty("974")] public int x974 { get; set; }
        [GameProperty("975")] public int x975 { get; set; }
        [GameProperty("976")] public int x976 { get; set; }
        [GameProperty("977")] public int x977 { get; set; }
        [GameProperty("978")] public int x978 { get; set; }
        [GameProperty("979")] public int x979 { get; set; }
        [GameProperty("980")] public int x980 { get; set; }
        [GameProperty("981")] public int x981 { get; set; }
        [GameProperty("982")] public int x982 { get; set; }
        [GameProperty("983")] public int x983 { get; set; }
        [GameProperty("984")] public int x984 { get; set; }
        [GameProperty("985")] public int x985 { get; set; }
        [GameProperty("986")] public int x986 { get; set; }
        [GameProperty("987")] public int x987 { get; set; }
        [GameProperty("988")] public int x988 { get; set; }
        [GameProperty("989")] public int x989 { get; set; }
        [GameProperty("990")] public int x990 { get; set; }
        [GameProperty("991")] public int x991 { get; set; }
        [GameProperty("992")] public int x992 { get; set; }
        [GameProperty("993")] public int x993 { get; set; }
        [GameProperty("994")] public int x994 { get; set; }
        [GameProperty("995")] public int x995 { get; set; }
        [GameProperty("996")] public int x996 { get; set; }
        [GameProperty("997")] public int x997 { get; set; }
        [GameProperty("998")] public int x998 { get; set; }
        [GameProperty("999")] public int x999 { get; set; }
        [GameProperty("1000")] public int x1000 { get; set; }

        public override string ParserSense => ":";
    }
}